module:
  imports:
    - path: github.com/lingeringcode/lndgrn-cv-hero
    - path: github.com/hugomods/icons/vendors/font-awesome
    - path: github.com/hugomods/icons/vendors/bootstrap
    - path: github.com/hugomods/icons/vendors/simple-icons